### ISSUE TITLE
Timed Vault Mechanic

### ISSUE THREAD

**Issue by xanderdunn** [erasureprotocol/NMR#64]
In the future, we'll consider implementing a timed vault mechanic for large Numeraire transfers, as outlined [here](http://hackingdistributed.com/2016/02/26/how-to-implement-secure-bitcoin-vaults/).

@philipcmonk pointed out we can create a new contract for this and transfer ownership to it.

**Comment by vessenes** [comment]
It might be worth reading up on ERC223, which is still rough and in progress, https://github.com/ethereum/EIPs/issues/223. Support for calling functions out to other contracts goes a long way toward future-proofing features like this.
