### ISSUE TITLE
Partially Return Stake

### ISSUE THREAD

**Issue by xanderdunn** [erasureprotocol/NMR#69]
Upgrade the contract so that a given stake can be partially returned and partially destroyed.  This is so that we can resolve a stake worse than random that is on the edge of the prize pool by destroying an amount of the stake proportional to the amount of prize pool that's left.  In general, "You should have destroyed the amount of NMR proportional to what you stand to win."

Until this is done at some point in the future, we will resolve the stake this worse than random stake on the edge of the prize pool by returning all its NMR.

**Comment by philipcmonk** [comment]
The whitepaper should also be updated to specify this.
